apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: funnyfoxd/frontend-ldap:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
